<?xml version="1.0" encoding="utf-8"?><Database Name="master" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\SQLEXPRESS;Initial Catalog=master;Integrated Security=True" SettingsObjectName="LINQAgain.Properties.Settings" SettingsPropertyName="masterConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.BSOM_DataSet_revised" Member="BSOM_DataSet_reviseds">
    <Type Name="BSOM_DataSet_revised">
      <Column Name="STEP_1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Random_ID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="O1_PI_01" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="O1_PI_02" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="O1_PI_03" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="O1_PI_04" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="O1_PI_05" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="O1_PI_06" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="O1_PI_07" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="O1_PI_08" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="O1_PI_09" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="O1_PI_10" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="O1_PI_11" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="O1_PI_12" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="O1_PI_13" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="O2_PI_01" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="O2_PI_02" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="O2_PI_03" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="O2_PI_04" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="O2_PI_05" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="O2_PI_06" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="O2_PI_07" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="O2_PI_08" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="O2_PI_09" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="O2_PI_10" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="O2_PI_11" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="O2_PI_12" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="O2_PI_13" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HA_PI_01" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HA_PI_02" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HA_PI_03" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HA_PI_04" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HD_PI_01" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HD_PI_02" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HD_PI_03" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HD_PI_04" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HD_PI_05" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HD_PI_06" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HD_PI_07" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HD_PI_08" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HD_PI_09" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HD_PI_10" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HD_PI_11" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HD_PI_12" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HD_PI_13" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HD_PI_14" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HD_PI_15" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SA_PI_01" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SA_PI_02" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SA_PI_03" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SA_PI_04" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SA_PI_05" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SA_PI_06" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SA_PI_07" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SA_PI_08" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SA_PI_09" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SA_PI_10" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SA_PI_11" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SA_PI_12" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SA_PI_13" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SA_PI_14" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SA_PI_15" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SA_PI_16" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SA_PI_17" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SA_PI_18" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SA_PI_19" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SA_PI_20" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SA_PI_21" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SA_PI_22" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SA_PI_23" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SA_PI_24" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SA_PI_25" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SA_PI_26" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="B2E_PI_01" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="B2E_PI_02" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="B2E_PI_03" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="B2E_PI_04" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="B2E_PI_05" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="B2E_PI_06" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="B2E_PI_07" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="B2E_PI_08" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="B2E_PI_09" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="B2E_PI_10" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="B2E_PI_11" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="B2E_PI_12" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="B2E_PI_13" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="B2E_PI_14" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="B2E_PI_15" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="B2E_PI_16" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="B2E_PI_17" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="B2E_PI_18" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="B2E_PI_19" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="B2E_PI_20" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="B2E_PI_21" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="B2E_PI_22" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="B2E_PI_23" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="B2E_PI_24" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="B2E_PI_25" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="B2E_PI_26" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="B2E_PI_27" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="B2E_PI_28" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="B2E_PI_29" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="B2E_PI_30" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BCR_PI_01" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BCR_PI_02" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BCR_PI_03" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BCR_PI_04" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BCR_PI_06" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BCR_PI_07" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BCR_PI_08" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BCR_PI_09" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BCR_PI_10" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BCR_PI_11" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BCR_PI_12" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BCR_PI_13" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BCR_PI_14" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BCR_PI_15" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BCR_PI_16" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BCR_PI_17" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BCR_PI_18" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BCR_PI_19" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BCR_PI_20" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BCR_PI_21" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BCR_PI_22" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BCR_PI_23" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BCR_PI_24" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BCR_PI_25" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BCR_PI_26" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BCR_PI_27" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BCR_PI_28" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BCR_PI_29" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BCR_PI_30" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BCR_PI_31" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="O1_IRAT_01" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="O1_IRAT_02" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="O1_IRAT_03" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="O1_IRAT_04" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="O1_IRAT_05" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="O1_IRAT_06" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="O1_IRAT_07" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="O1_IRAT_08" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="O1_IRAT_09" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="O1_IRAT_10" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="O1_IRAT_11" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="O1_IRAT_12" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="O2_IRAT_01" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="O2_IRAT_02" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HA_IRAT_01" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HA_IRAT_02" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HD_IRAT_01" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HD_IRAT_02" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SA_IRAT_01" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SA_IRAT_02" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SA_IRAT_03" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SA_IRAT_04" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SA_IRAT_05" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SA_IRAT_06" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SA_IRAT_07" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="B2E_IRAT_01" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="B2E_IRAT_02" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="B2E_IRAT_03" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="B2E_IRAT_04" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="B2E_IRAT_05" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="B2E_IRAT_06" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BCR_IRAT_01" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BCR_IRAT_02" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BCR_IRAT_03" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="O1_MCQ1_IND" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="O1_MCQ1_GRP" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="O1_MCQ1_TOT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="O1_MCQ2_IND" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="O1_MCQ2_GRP" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="O1_MCQ2_TOT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="O1_MCQ3_IND" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="O1_MCQ3_GRP" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="O1_MCQ3_TOT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="O2_MCQ1_IND" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="O2_MCQ1_GRP" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="O2_MCQ1_TOT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="O2_MCQ2_IND" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="O2_MCQ2_GRP" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="O2_MCQ2_TOT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="O2_MCQ3_IND" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="O2_MCQ3_GRP" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="O2_MCQ3_TOT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HD_MCQ1_IND" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HD_MCQ1_GRP" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HD_MCQ1_TOT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SA_MCQ1_IND" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SA_MCQ1_GRP" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SA_MCQ1_TOT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SA_MCQ2_IND" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SA_MCQ2_GRP" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SA_MCQ2_TOT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SA_MCQ3_IND" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SA_MCQ3_GRP" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SA_MCQ3_TOT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SA_MCQ4_IND" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SA_MCQ4_GRP" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SA_MCQ4_TOT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SA_MCQ5_IND" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SA_MCQ5_GRP" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SA_MCQ5_TOT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="O1_PI_AVG_13" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="O2_PI_AVG_13" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="O1O2_PI_AVG_26" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HA_PI_AVG_04" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HD_PI_AVG_15" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SA_PI_AVG_26" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="B2E_PI_AVG_30" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BCR_PI_AVG_30" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="O1_IRAT_AVG_12" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="O2_IRAT_AVG_02" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HA_IRAT_AVG_02" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HD_IRAT_AVG_02" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SA_IRAT_AVG_07" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="B2E_IRAT_AVG_06" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BCR_IRAT_AVG_03" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="O1_MCQ_AVG_03" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="O2_MCQ_AVG_03" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HD_MCQ_AVG_01" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SA_MCQ_AVG_05" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="B2E_MCQ_AVG_04" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BCR_MCQ_AVG_04" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BCR_ANAT_MCQ_AVG_02" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="all_NBME_avg_n4" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="all_mcqs_avg_n20" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="all_irats_avg_n34" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="all_PIs_avg_n131" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BCR_NBME_final" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="B2E_NBME_final" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="O1_O2_NBME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SA_NBME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HA_final" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HD_final" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CBSE_01" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CBSE_02" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>