#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LINQAgain
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="master")]
	public partial class MedicalDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public MedicalDataContext() : 
				base(global::LINQAgain.Properties.Settings.Default.masterConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MedicalDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MedicalDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MedicalDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MedicalDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BSOM_DataSet_revised> BSOM_DataSet_reviseds
		{
			get
			{
				return this.GetTable<BSOM_DataSet_revised>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BSOM_DataSet_revised")]
	public partial class BSOM_DataSet_revised
	{
		
		private string _STEP_1;
		
		private string _Random_ID;
		
		private string _O1_PI_01;
		
		private string _O1_PI_02;
		
		private string _O1_PI_03;
		
		private string _O1_PI_04;
		
		private string _O1_PI_05;
		
		private string _O1_PI_06;
		
		private string _O1_PI_07;
		
		private string _O1_PI_08;
		
		private string _O1_PI_09;
		
		private string _O1_PI_10;
		
		private string _O1_PI_11;
		
		private string _O1_PI_12;
		
		private string _O1_PI_13;
		
		private string _O2_PI_01;
		
		private string _O2_PI_02;
		
		private string _O2_PI_03;
		
		private string _O2_PI_04;
		
		private string _O2_PI_05;
		
		private string _O2_PI_06;
		
		private string _O2_PI_07;
		
		private string _O2_PI_08;
		
		private string _O2_PI_09;
		
		private string _O2_PI_10;
		
		private string _O2_PI_11;
		
		private string _O2_PI_12;
		
		private string _O2_PI_13;
		
		private string _HA_PI_01;
		
		private string _HA_PI_02;
		
		private string _HA_PI_03;
		
		private string _HA_PI_04;
		
		private string _HD_PI_01;
		
		private string _HD_PI_02;
		
		private string _HD_PI_03;
		
		private string _HD_PI_04;
		
		private string _HD_PI_05;
		
		private string _HD_PI_06;
		
		private string _HD_PI_07;
		
		private string _HD_PI_08;
		
		private string _HD_PI_09;
		
		private string _HD_PI_10;
		
		private string _HD_PI_11;
		
		private string _HD_PI_12;
		
		private string _HD_PI_13;
		
		private string _HD_PI_14;
		
		private string _HD_PI_15;
		
		private string _SA_PI_01;
		
		private string _SA_PI_02;
		
		private string _SA_PI_03;
		
		private string _SA_PI_04;
		
		private string _SA_PI_05;
		
		private string _SA_PI_06;
		
		private string _SA_PI_07;
		
		private string _SA_PI_08;
		
		private string _SA_PI_09;
		
		private string _SA_PI_10;
		
		private string _SA_PI_11;
		
		private string _SA_PI_12;
		
		private string _SA_PI_13;
		
		private string _SA_PI_14;
		
		private string _SA_PI_15;
		
		private string _SA_PI_16;
		
		private string _SA_PI_17;
		
		private string _SA_PI_18;
		
		private string _SA_PI_19;
		
		private string _SA_PI_20;
		
		private string _SA_PI_21;
		
		private string _SA_PI_22;
		
		private string _SA_PI_23;
		
		private string _SA_PI_24;
		
		private string _SA_PI_25;
		
		private string _SA_PI_26;
		
		private string _B2E_PI_01;
		
		private string _B2E_PI_02;
		
		private string _B2E_PI_03;
		
		private string _B2E_PI_04;
		
		private string _B2E_PI_05;
		
		private string _B2E_PI_06;
		
		private string _B2E_PI_07;
		
		private string _B2E_PI_08;
		
		private string _B2E_PI_09;
		
		private string _B2E_PI_10;
		
		private string _B2E_PI_11;
		
		private string _B2E_PI_12;
		
		private string _B2E_PI_13;
		
		private string _B2E_PI_14;
		
		private string _B2E_PI_15;
		
		private string _B2E_PI_16;
		
		private string _B2E_PI_17;
		
		private string _B2E_PI_18;
		
		private string _B2E_PI_19;
		
		private string _B2E_PI_20;
		
		private string _B2E_PI_21;
		
		private string _B2E_PI_22;
		
		private string _B2E_PI_23;
		
		private string _B2E_PI_24;
		
		private string _B2E_PI_25;
		
		private string _B2E_PI_26;
		
		private string _B2E_PI_27;
		
		private string _B2E_PI_28;
		
		private string _B2E_PI_29;
		
		private string _B2E_PI_30;
		
		private string _BCR_PI_01;
		
		private string _BCR_PI_02;
		
		private string _BCR_PI_03;
		
		private string _BCR_PI_04;
		
		private string _BCR_PI_06;
		
		private string _BCR_PI_07;
		
		private string _BCR_PI_08;
		
		private string _BCR_PI_09;
		
		private string _BCR_PI_10;
		
		private string _BCR_PI_11;
		
		private string _BCR_PI_12;
		
		private string _BCR_PI_13;
		
		private string _BCR_PI_14;
		
		private string _BCR_PI_15;
		
		private string _BCR_PI_16;
		
		private string _BCR_PI_17;
		
		private string _BCR_PI_18;
		
		private string _BCR_PI_19;
		
		private string _BCR_PI_20;
		
		private string _BCR_PI_21;
		
		private string _BCR_PI_22;
		
		private string _BCR_PI_23;
		
		private string _BCR_PI_24;
		
		private string _BCR_PI_25;
		
		private string _BCR_PI_26;
		
		private string _BCR_PI_27;
		
		private string _BCR_PI_28;
		
		private string _BCR_PI_29;
		
		private string _BCR_PI_30;
		
		private string _BCR_PI_31;
		
		private string _O1_IRAT_01;
		
		private string _O1_IRAT_02;
		
		private string _O1_IRAT_03;
		
		private string _O1_IRAT_04;
		
		private string _O1_IRAT_05;
		
		private string _O1_IRAT_06;
		
		private string _O1_IRAT_07;
		
		private string _O1_IRAT_08;
		
		private string _O1_IRAT_09;
		
		private string _O1_IRAT_10;
		
		private string _O1_IRAT_11;
		
		private string _O1_IRAT_12;
		
		private string _O2_IRAT_01;
		
		private string _O2_IRAT_02;
		
		private string _HA_IRAT_01;
		
		private string _HA_IRAT_02;
		
		private string _HD_IRAT_01;
		
		private string _HD_IRAT_02;
		
		private string _SA_IRAT_01;
		
		private string _SA_IRAT_02;
		
		private string _SA_IRAT_03;
		
		private string _SA_IRAT_04;
		
		private string _SA_IRAT_05;
		
		private string _SA_IRAT_06;
		
		private string _SA_IRAT_07;
		
		private string _B2E_IRAT_01;
		
		private string _B2E_IRAT_02;
		
		private string _B2E_IRAT_03;
		
		private string _B2E_IRAT_04;
		
		private string _B2E_IRAT_05;
		
		private string _B2E_IRAT_06;
		
		private string _BCR_IRAT_01;
		
		private string _BCR_IRAT_02;
		
		private string _BCR_IRAT_03;
		
		private string _O1_MCQ1_IND;
		
		private string _O1_MCQ1_GRP;
		
		private string _O1_MCQ1_TOT;
		
		private string _O1_MCQ2_IND;
		
		private string _O1_MCQ2_GRP;
		
		private string _O1_MCQ2_TOT;
		
		private string _O1_MCQ3_IND;
		
		private string _O1_MCQ3_GRP;
		
		private string _O1_MCQ3_TOT;
		
		private string _O2_MCQ1_IND;
		
		private string _O2_MCQ1_GRP;
		
		private string _O2_MCQ1_TOT;
		
		private string _O2_MCQ2_IND;
		
		private string _O2_MCQ2_GRP;
		
		private string _O2_MCQ2_TOT;
		
		private string _O2_MCQ3_IND;
		
		private string _O2_MCQ3_GRP;
		
		private string _O2_MCQ3_TOT;
		
		private string _HD_MCQ1_IND;
		
		private string _HD_MCQ1_GRP;
		
		private string _HD_MCQ1_TOT;
		
		private string _SA_MCQ1_IND;
		
		private string _SA_MCQ1_GRP;
		
		private string _SA_MCQ1_TOT;
		
		private string _SA_MCQ2_IND;
		
		private string _SA_MCQ2_GRP;
		
		private string _SA_MCQ2_TOT;
		
		private string _SA_MCQ3_IND;
		
		private string _SA_MCQ3_GRP;
		
		private string _SA_MCQ3_TOT;
		
		private string _SA_MCQ4_IND;
		
		private string _SA_MCQ4_GRP;
		
		private string _SA_MCQ4_TOT;
		
		private string _SA_MCQ5_IND;
		
		private string _SA_MCQ5_GRP;
		
		private string _SA_MCQ5_TOT;
		
		private string _O1_PI_AVG_13;
		
		private string _O2_PI_AVG_13;
		
		private string _O1O2_PI_AVG_26;
		
		private string _HA_PI_AVG_04;
		
		private string _HD_PI_AVG_15;
		
		private string _SA_PI_AVG_26;
		
		private string _B2E_PI_AVG_30;
		
		private string _BCR_PI_AVG_30;
		
		private string _O1_IRAT_AVG_12;
		
		private string _O2_IRAT_AVG_02;
		
		private string _HA_IRAT_AVG_02;
		
		private string _HD_IRAT_AVG_02;
		
		private string _SA_IRAT_AVG_07;
		
		private string _B2E_IRAT_AVG_06;
		
		private string _BCR_IRAT_AVG_03;
		
		private string _O1_MCQ_AVG_03;
		
		private string _O2_MCQ_AVG_03;
		
		private string _HD_MCQ_AVG_01;
		
		private string _SA_MCQ_AVG_05;
		
		private string _B2E_MCQ_AVG_04;
		
		private string _BCR_MCQ_AVG_04;
		
		private string _BCR_ANAT_MCQ_AVG_02;
		
		private string _all_NBME_avg_n4;
		
		private string _all_mcqs_avg_n20;
		
		private string _all_irats_avg_n34;
		
		private string _all_PIs_avg_n131;
		
		private string _BCR_NBME_final;
		
		private string _B2E_NBME_final;
		
		private string _O1_O2_NBME;
		
		private string _SA_NBME;
		
		private string _HA_final;
		
		private string _HD_final;
		
		private string _CBSE_01;
		
		private string _CBSE_02;
		
		public BSOM_DataSet_revised()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STEP_1", DbType="VarChar(50)")]
		public string STEP_1
		{
			get
			{
				return this._STEP_1;
			}
			set
			{
				if ((this._STEP_1 != value))
				{
					this._STEP_1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Random_ID", DbType="VarChar(50)")]
		public string Random_ID
		{
			get
			{
				return this._Random_ID;
			}
			set
			{
				if ((this._Random_ID != value))
				{
					this._Random_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O1_PI_01", DbType="VarChar(50)")]
		public string O1_PI_01
		{
			get
			{
				return this._O1_PI_01;
			}
			set
			{
				if ((this._O1_PI_01 != value))
				{
					this._O1_PI_01 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O1_PI_02", DbType="VarChar(50)")]
		public string O1_PI_02
		{
			get
			{
				return this._O1_PI_02;
			}
			set
			{
				if ((this._O1_PI_02 != value))
				{
					this._O1_PI_02 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O1_PI_03", DbType="VarChar(50)")]
		public string O1_PI_03
		{
			get
			{
				return this._O1_PI_03;
			}
			set
			{
				if ((this._O1_PI_03 != value))
				{
					this._O1_PI_03 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O1_PI_04", DbType="VarChar(50)")]
		public string O1_PI_04
		{
			get
			{
				return this._O1_PI_04;
			}
			set
			{
				if ((this._O1_PI_04 != value))
				{
					this._O1_PI_04 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O1_PI_05", DbType="VarChar(50)")]
		public string O1_PI_05
		{
			get
			{
				return this._O1_PI_05;
			}
			set
			{
				if ((this._O1_PI_05 != value))
				{
					this._O1_PI_05 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O1_PI_06", DbType="VarChar(50)")]
		public string O1_PI_06
		{
			get
			{
				return this._O1_PI_06;
			}
			set
			{
				if ((this._O1_PI_06 != value))
				{
					this._O1_PI_06 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O1_PI_07", DbType="VarChar(50)")]
		public string O1_PI_07
		{
			get
			{
				return this._O1_PI_07;
			}
			set
			{
				if ((this._O1_PI_07 != value))
				{
					this._O1_PI_07 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O1_PI_08", DbType="VarChar(50)")]
		public string O1_PI_08
		{
			get
			{
				return this._O1_PI_08;
			}
			set
			{
				if ((this._O1_PI_08 != value))
				{
					this._O1_PI_08 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O1_PI_09", DbType="VarChar(50)")]
		public string O1_PI_09
		{
			get
			{
				return this._O1_PI_09;
			}
			set
			{
				if ((this._O1_PI_09 != value))
				{
					this._O1_PI_09 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O1_PI_10", DbType="VarChar(50)")]
		public string O1_PI_10
		{
			get
			{
				return this._O1_PI_10;
			}
			set
			{
				if ((this._O1_PI_10 != value))
				{
					this._O1_PI_10 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O1_PI_11", DbType="VarChar(50)")]
		public string O1_PI_11
		{
			get
			{
				return this._O1_PI_11;
			}
			set
			{
				if ((this._O1_PI_11 != value))
				{
					this._O1_PI_11 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O1_PI_12", DbType="VarChar(50)")]
		public string O1_PI_12
		{
			get
			{
				return this._O1_PI_12;
			}
			set
			{
				if ((this._O1_PI_12 != value))
				{
					this._O1_PI_12 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O1_PI_13", DbType="VarChar(50)")]
		public string O1_PI_13
		{
			get
			{
				return this._O1_PI_13;
			}
			set
			{
				if ((this._O1_PI_13 != value))
				{
					this._O1_PI_13 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O2_PI_01", DbType="VarChar(50)")]
		public string O2_PI_01
		{
			get
			{
				return this._O2_PI_01;
			}
			set
			{
				if ((this._O2_PI_01 != value))
				{
					this._O2_PI_01 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O2_PI_02", DbType="VarChar(50)")]
		public string O2_PI_02
		{
			get
			{
				return this._O2_PI_02;
			}
			set
			{
				if ((this._O2_PI_02 != value))
				{
					this._O2_PI_02 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O2_PI_03", DbType="VarChar(50)")]
		public string O2_PI_03
		{
			get
			{
				return this._O2_PI_03;
			}
			set
			{
				if ((this._O2_PI_03 != value))
				{
					this._O2_PI_03 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O2_PI_04", DbType="VarChar(50)")]
		public string O2_PI_04
		{
			get
			{
				return this._O2_PI_04;
			}
			set
			{
				if ((this._O2_PI_04 != value))
				{
					this._O2_PI_04 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O2_PI_05", DbType="VarChar(50)")]
		public string O2_PI_05
		{
			get
			{
				return this._O2_PI_05;
			}
			set
			{
				if ((this._O2_PI_05 != value))
				{
					this._O2_PI_05 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O2_PI_06", DbType="VarChar(50)")]
		public string O2_PI_06
		{
			get
			{
				return this._O2_PI_06;
			}
			set
			{
				if ((this._O2_PI_06 != value))
				{
					this._O2_PI_06 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O2_PI_07", DbType="VarChar(50)")]
		public string O2_PI_07
		{
			get
			{
				return this._O2_PI_07;
			}
			set
			{
				if ((this._O2_PI_07 != value))
				{
					this._O2_PI_07 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O2_PI_08", DbType="VarChar(50)")]
		public string O2_PI_08
		{
			get
			{
				return this._O2_PI_08;
			}
			set
			{
				if ((this._O2_PI_08 != value))
				{
					this._O2_PI_08 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O2_PI_09", DbType="VarChar(50)")]
		public string O2_PI_09
		{
			get
			{
				return this._O2_PI_09;
			}
			set
			{
				if ((this._O2_PI_09 != value))
				{
					this._O2_PI_09 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O2_PI_10", DbType="VarChar(50)")]
		public string O2_PI_10
		{
			get
			{
				return this._O2_PI_10;
			}
			set
			{
				if ((this._O2_PI_10 != value))
				{
					this._O2_PI_10 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O2_PI_11", DbType="VarChar(50)")]
		public string O2_PI_11
		{
			get
			{
				return this._O2_PI_11;
			}
			set
			{
				if ((this._O2_PI_11 != value))
				{
					this._O2_PI_11 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O2_PI_12", DbType="VarChar(50)")]
		public string O2_PI_12
		{
			get
			{
				return this._O2_PI_12;
			}
			set
			{
				if ((this._O2_PI_12 != value))
				{
					this._O2_PI_12 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O2_PI_13", DbType="VarChar(50)")]
		public string O2_PI_13
		{
			get
			{
				return this._O2_PI_13;
			}
			set
			{
				if ((this._O2_PI_13 != value))
				{
					this._O2_PI_13 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HA_PI_01", DbType="VarChar(50)")]
		public string HA_PI_01
		{
			get
			{
				return this._HA_PI_01;
			}
			set
			{
				if ((this._HA_PI_01 != value))
				{
					this._HA_PI_01 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HA_PI_02", DbType="VarChar(50)")]
		public string HA_PI_02
		{
			get
			{
				return this._HA_PI_02;
			}
			set
			{
				if ((this._HA_PI_02 != value))
				{
					this._HA_PI_02 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HA_PI_03", DbType="VarChar(50)")]
		public string HA_PI_03
		{
			get
			{
				return this._HA_PI_03;
			}
			set
			{
				if ((this._HA_PI_03 != value))
				{
					this._HA_PI_03 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HA_PI_04", DbType="VarChar(50)")]
		public string HA_PI_04
		{
			get
			{
				return this._HA_PI_04;
			}
			set
			{
				if ((this._HA_PI_04 != value))
				{
					this._HA_PI_04 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HD_PI_01", DbType="VarChar(50)")]
		public string HD_PI_01
		{
			get
			{
				return this._HD_PI_01;
			}
			set
			{
				if ((this._HD_PI_01 != value))
				{
					this._HD_PI_01 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HD_PI_02", DbType="VarChar(50)")]
		public string HD_PI_02
		{
			get
			{
				return this._HD_PI_02;
			}
			set
			{
				if ((this._HD_PI_02 != value))
				{
					this._HD_PI_02 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HD_PI_03", DbType="VarChar(50)")]
		public string HD_PI_03
		{
			get
			{
				return this._HD_PI_03;
			}
			set
			{
				if ((this._HD_PI_03 != value))
				{
					this._HD_PI_03 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HD_PI_04", DbType="VarChar(50)")]
		public string HD_PI_04
		{
			get
			{
				return this._HD_PI_04;
			}
			set
			{
				if ((this._HD_PI_04 != value))
				{
					this._HD_PI_04 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HD_PI_05", DbType="VarChar(50)")]
		public string HD_PI_05
		{
			get
			{
				return this._HD_PI_05;
			}
			set
			{
				if ((this._HD_PI_05 != value))
				{
					this._HD_PI_05 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HD_PI_06", DbType="VarChar(50)")]
		public string HD_PI_06
		{
			get
			{
				return this._HD_PI_06;
			}
			set
			{
				if ((this._HD_PI_06 != value))
				{
					this._HD_PI_06 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HD_PI_07", DbType="VarChar(50)")]
		public string HD_PI_07
		{
			get
			{
				return this._HD_PI_07;
			}
			set
			{
				if ((this._HD_PI_07 != value))
				{
					this._HD_PI_07 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HD_PI_08", DbType="VarChar(50)")]
		public string HD_PI_08
		{
			get
			{
				return this._HD_PI_08;
			}
			set
			{
				if ((this._HD_PI_08 != value))
				{
					this._HD_PI_08 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HD_PI_09", DbType="VarChar(50)")]
		public string HD_PI_09
		{
			get
			{
				return this._HD_PI_09;
			}
			set
			{
				if ((this._HD_PI_09 != value))
				{
					this._HD_PI_09 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HD_PI_10", DbType="VarChar(50)")]
		public string HD_PI_10
		{
			get
			{
				return this._HD_PI_10;
			}
			set
			{
				if ((this._HD_PI_10 != value))
				{
					this._HD_PI_10 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HD_PI_11", DbType="VarChar(50)")]
		public string HD_PI_11
		{
			get
			{
				return this._HD_PI_11;
			}
			set
			{
				if ((this._HD_PI_11 != value))
				{
					this._HD_PI_11 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HD_PI_12", DbType="VarChar(50)")]
		public string HD_PI_12
		{
			get
			{
				return this._HD_PI_12;
			}
			set
			{
				if ((this._HD_PI_12 != value))
				{
					this._HD_PI_12 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HD_PI_13", DbType="VarChar(50)")]
		public string HD_PI_13
		{
			get
			{
				return this._HD_PI_13;
			}
			set
			{
				if ((this._HD_PI_13 != value))
				{
					this._HD_PI_13 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HD_PI_14", DbType="VarChar(50)")]
		public string HD_PI_14
		{
			get
			{
				return this._HD_PI_14;
			}
			set
			{
				if ((this._HD_PI_14 != value))
				{
					this._HD_PI_14 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HD_PI_15", DbType="VarChar(50)")]
		public string HD_PI_15
		{
			get
			{
				return this._HD_PI_15;
			}
			set
			{
				if ((this._HD_PI_15 != value))
				{
					this._HD_PI_15 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SA_PI_01", DbType="VarChar(50)")]
		public string SA_PI_01
		{
			get
			{
				return this._SA_PI_01;
			}
			set
			{
				if ((this._SA_PI_01 != value))
				{
					this._SA_PI_01 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SA_PI_02", DbType="VarChar(50)")]
		public string SA_PI_02
		{
			get
			{
				return this._SA_PI_02;
			}
			set
			{
				if ((this._SA_PI_02 != value))
				{
					this._SA_PI_02 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SA_PI_03", DbType="VarChar(50)")]
		public string SA_PI_03
		{
			get
			{
				return this._SA_PI_03;
			}
			set
			{
				if ((this._SA_PI_03 != value))
				{
					this._SA_PI_03 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SA_PI_04", DbType="VarChar(50)")]
		public string SA_PI_04
		{
			get
			{
				return this._SA_PI_04;
			}
			set
			{
				if ((this._SA_PI_04 != value))
				{
					this._SA_PI_04 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SA_PI_05", DbType="VarChar(50)")]
		public string SA_PI_05
		{
			get
			{
				return this._SA_PI_05;
			}
			set
			{
				if ((this._SA_PI_05 != value))
				{
					this._SA_PI_05 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SA_PI_06", DbType="VarChar(50)")]
		public string SA_PI_06
		{
			get
			{
				return this._SA_PI_06;
			}
			set
			{
				if ((this._SA_PI_06 != value))
				{
					this._SA_PI_06 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SA_PI_07", DbType="VarChar(50)")]
		public string SA_PI_07
		{
			get
			{
				return this._SA_PI_07;
			}
			set
			{
				if ((this._SA_PI_07 != value))
				{
					this._SA_PI_07 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SA_PI_08", DbType="VarChar(50)")]
		public string SA_PI_08
		{
			get
			{
				return this._SA_PI_08;
			}
			set
			{
				if ((this._SA_PI_08 != value))
				{
					this._SA_PI_08 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SA_PI_09", DbType="VarChar(50)")]
		public string SA_PI_09
		{
			get
			{
				return this._SA_PI_09;
			}
			set
			{
				if ((this._SA_PI_09 != value))
				{
					this._SA_PI_09 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SA_PI_10", DbType="VarChar(50)")]
		public string SA_PI_10
		{
			get
			{
				return this._SA_PI_10;
			}
			set
			{
				if ((this._SA_PI_10 != value))
				{
					this._SA_PI_10 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SA_PI_11", DbType="VarChar(50)")]
		public string SA_PI_11
		{
			get
			{
				return this._SA_PI_11;
			}
			set
			{
				if ((this._SA_PI_11 != value))
				{
					this._SA_PI_11 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SA_PI_12", DbType="VarChar(50)")]
		public string SA_PI_12
		{
			get
			{
				return this._SA_PI_12;
			}
			set
			{
				if ((this._SA_PI_12 != value))
				{
					this._SA_PI_12 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SA_PI_13", DbType="VarChar(50)")]
		public string SA_PI_13
		{
			get
			{
				return this._SA_PI_13;
			}
			set
			{
				if ((this._SA_PI_13 != value))
				{
					this._SA_PI_13 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SA_PI_14", DbType="VarChar(50)")]
		public string SA_PI_14
		{
			get
			{
				return this._SA_PI_14;
			}
			set
			{
				if ((this._SA_PI_14 != value))
				{
					this._SA_PI_14 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SA_PI_15", DbType="VarChar(50)")]
		public string SA_PI_15
		{
			get
			{
				return this._SA_PI_15;
			}
			set
			{
				if ((this._SA_PI_15 != value))
				{
					this._SA_PI_15 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SA_PI_16", DbType="VarChar(50)")]
		public string SA_PI_16
		{
			get
			{
				return this._SA_PI_16;
			}
			set
			{
				if ((this._SA_PI_16 != value))
				{
					this._SA_PI_16 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SA_PI_17", DbType="VarChar(50)")]
		public string SA_PI_17
		{
			get
			{
				return this._SA_PI_17;
			}
			set
			{
				if ((this._SA_PI_17 != value))
				{
					this._SA_PI_17 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SA_PI_18", DbType="VarChar(50)")]
		public string SA_PI_18
		{
			get
			{
				return this._SA_PI_18;
			}
			set
			{
				if ((this._SA_PI_18 != value))
				{
					this._SA_PI_18 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SA_PI_19", DbType="VarChar(50)")]
		public string SA_PI_19
		{
			get
			{
				return this._SA_PI_19;
			}
			set
			{
				if ((this._SA_PI_19 != value))
				{
					this._SA_PI_19 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SA_PI_20", DbType="VarChar(50)")]
		public string SA_PI_20
		{
			get
			{
				return this._SA_PI_20;
			}
			set
			{
				if ((this._SA_PI_20 != value))
				{
					this._SA_PI_20 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SA_PI_21", DbType="VarChar(50)")]
		public string SA_PI_21
		{
			get
			{
				return this._SA_PI_21;
			}
			set
			{
				if ((this._SA_PI_21 != value))
				{
					this._SA_PI_21 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SA_PI_22", DbType="VarChar(50)")]
		public string SA_PI_22
		{
			get
			{
				return this._SA_PI_22;
			}
			set
			{
				if ((this._SA_PI_22 != value))
				{
					this._SA_PI_22 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SA_PI_23", DbType="VarChar(50)")]
		public string SA_PI_23
		{
			get
			{
				return this._SA_PI_23;
			}
			set
			{
				if ((this._SA_PI_23 != value))
				{
					this._SA_PI_23 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SA_PI_24", DbType="VarChar(50)")]
		public string SA_PI_24
		{
			get
			{
				return this._SA_PI_24;
			}
			set
			{
				if ((this._SA_PI_24 != value))
				{
					this._SA_PI_24 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SA_PI_25", DbType="VarChar(50)")]
		public string SA_PI_25
		{
			get
			{
				return this._SA_PI_25;
			}
			set
			{
				if ((this._SA_PI_25 != value))
				{
					this._SA_PI_25 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SA_PI_26", DbType="VarChar(50)")]
		public string SA_PI_26
		{
			get
			{
				return this._SA_PI_26;
			}
			set
			{
				if ((this._SA_PI_26 != value))
				{
					this._SA_PI_26 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B2E_PI_01", DbType="VarChar(50)")]
		public string B2E_PI_01
		{
			get
			{
				return this._B2E_PI_01;
			}
			set
			{
				if ((this._B2E_PI_01 != value))
				{
					this._B2E_PI_01 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B2E_PI_02", DbType="VarChar(50)")]
		public string B2E_PI_02
		{
			get
			{
				return this._B2E_PI_02;
			}
			set
			{
				if ((this._B2E_PI_02 != value))
				{
					this._B2E_PI_02 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B2E_PI_03", DbType="VarChar(50)")]
		public string B2E_PI_03
		{
			get
			{
				return this._B2E_PI_03;
			}
			set
			{
				if ((this._B2E_PI_03 != value))
				{
					this._B2E_PI_03 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B2E_PI_04", DbType="VarChar(50)")]
		public string B2E_PI_04
		{
			get
			{
				return this._B2E_PI_04;
			}
			set
			{
				if ((this._B2E_PI_04 != value))
				{
					this._B2E_PI_04 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B2E_PI_05", DbType="VarChar(50)")]
		public string B2E_PI_05
		{
			get
			{
				return this._B2E_PI_05;
			}
			set
			{
				if ((this._B2E_PI_05 != value))
				{
					this._B2E_PI_05 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B2E_PI_06", DbType="VarChar(50)")]
		public string B2E_PI_06
		{
			get
			{
				return this._B2E_PI_06;
			}
			set
			{
				if ((this._B2E_PI_06 != value))
				{
					this._B2E_PI_06 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B2E_PI_07", DbType="VarChar(50)")]
		public string B2E_PI_07
		{
			get
			{
				return this._B2E_PI_07;
			}
			set
			{
				if ((this._B2E_PI_07 != value))
				{
					this._B2E_PI_07 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B2E_PI_08", DbType="VarChar(50)")]
		public string B2E_PI_08
		{
			get
			{
				return this._B2E_PI_08;
			}
			set
			{
				if ((this._B2E_PI_08 != value))
				{
					this._B2E_PI_08 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B2E_PI_09", DbType="VarChar(50)")]
		public string B2E_PI_09
		{
			get
			{
				return this._B2E_PI_09;
			}
			set
			{
				if ((this._B2E_PI_09 != value))
				{
					this._B2E_PI_09 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B2E_PI_10", DbType="VarChar(50)")]
		public string B2E_PI_10
		{
			get
			{
				return this._B2E_PI_10;
			}
			set
			{
				if ((this._B2E_PI_10 != value))
				{
					this._B2E_PI_10 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B2E_PI_11", DbType="VarChar(50)")]
		public string B2E_PI_11
		{
			get
			{
				return this._B2E_PI_11;
			}
			set
			{
				if ((this._B2E_PI_11 != value))
				{
					this._B2E_PI_11 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B2E_PI_12", DbType="VarChar(50)")]
		public string B2E_PI_12
		{
			get
			{
				return this._B2E_PI_12;
			}
			set
			{
				if ((this._B2E_PI_12 != value))
				{
					this._B2E_PI_12 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B2E_PI_13", DbType="VarChar(50)")]
		public string B2E_PI_13
		{
			get
			{
				return this._B2E_PI_13;
			}
			set
			{
				if ((this._B2E_PI_13 != value))
				{
					this._B2E_PI_13 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B2E_PI_14", DbType="VarChar(50)")]
		public string B2E_PI_14
		{
			get
			{
				return this._B2E_PI_14;
			}
			set
			{
				if ((this._B2E_PI_14 != value))
				{
					this._B2E_PI_14 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B2E_PI_15", DbType="VarChar(50)")]
		public string B2E_PI_15
		{
			get
			{
				return this._B2E_PI_15;
			}
			set
			{
				if ((this._B2E_PI_15 != value))
				{
					this._B2E_PI_15 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B2E_PI_16", DbType="VarChar(50)")]
		public string B2E_PI_16
		{
			get
			{
				return this._B2E_PI_16;
			}
			set
			{
				if ((this._B2E_PI_16 != value))
				{
					this._B2E_PI_16 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B2E_PI_17", DbType="VarChar(50)")]
		public string B2E_PI_17
		{
			get
			{
				return this._B2E_PI_17;
			}
			set
			{
				if ((this._B2E_PI_17 != value))
				{
					this._B2E_PI_17 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B2E_PI_18", DbType="VarChar(50)")]
		public string B2E_PI_18
		{
			get
			{
				return this._B2E_PI_18;
			}
			set
			{
				if ((this._B2E_PI_18 != value))
				{
					this._B2E_PI_18 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B2E_PI_19", DbType="VarChar(50)")]
		public string B2E_PI_19
		{
			get
			{
				return this._B2E_PI_19;
			}
			set
			{
				if ((this._B2E_PI_19 != value))
				{
					this._B2E_PI_19 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B2E_PI_20", DbType="VarChar(50)")]
		public string B2E_PI_20
		{
			get
			{
				return this._B2E_PI_20;
			}
			set
			{
				if ((this._B2E_PI_20 != value))
				{
					this._B2E_PI_20 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B2E_PI_21", DbType="VarChar(50)")]
		public string B2E_PI_21
		{
			get
			{
				return this._B2E_PI_21;
			}
			set
			{
				if ((this._B2E_PI_21 != value))
				{
					this._B2E_PI_21 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B2E_PI_22", DbType="VarChar(50)")]
		public string B2E_PI_22
		{
			get
			{
				return this._B2E_PI_22;
			}
			set
			{
				if ((this._B2E_PI_22 != value))
				{
					this._B2E_PI_22 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B2E_PI_23", DbType="VarChar(50)")]
		public string B2E_PI_23
		{
			get
			{
				return this._B2E_PI_23;
			}
			set
			{
				if ((this._B2E_PI_23 != value))
				{
					this._B2E_PI_23 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B2E_PI_24", DbType="VarChar(50)")]
		public string B2E_PI_24
		{
			get
			{
				return this._B2E_PI_24;
			}
			set
			{
				if ((this._B2E_PI_24 != value))
				{
					this._B2E_PI_24 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B2E_PI_25", DbType="VarChar(50)")]
		public string B2E_PI_25
		{
			get
			{
				return this._B2E_PI_25;
			}
			set
			{
				if ((this._B2E_PI_25 != value))
				{
					this._B2E_PI_25 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B2E_PI_26", DbType="VarChar(50)")]
		public string B2E_PI_26
		{
			get
			{
				return this._B2E_PI_26;
			}
			set
			{
				if ((this._B2E_PI_26 != value))
				{
					this._B2E_PI_26 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B2E_PI_27", DbType="VarChar(50)")]
		public string B2E_PI_27
		{
			get
			{
				return this._B2E_PI_27;
			}
			set
			{
				if ((this._B2E_PI_27 != value))
				{
					this._B2E_PI_27 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B2E_PI_28", DbType="VarChar(50)")]
		public string B2E_PI_28
		{
			get
			{
				return this._B2E_PI_28;
			}
			set
			{
				if ((this._B2E_PI_28 != value))
				{
					this._B2E_PI_28 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B2E_PI_29", DbType="VarChar(50)")]
		public string B2E_PI_29
		{
			get
			{
				return this._B2E_PI_29;
			}
			set
			{
				if ((this._B2E_PI_29 != value))
				{
					this._B2E_PI_29 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B2E_PI_30", DbType="VarChar(50)")]
		public string B2E_PI_30
		{
			get
			{
				return this._B2E_PI_30;
			}
			set
			{
				if ((this._B2E_PI_30 != value))
				{
					this._B2E_PI_30 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BCR_PI_01", DbType="VarChar(50)")]
		public string BCR_PI_01
		{
			get
			{
				return this._BCR_PI_01;
			}
			set
			{
				if ((this._BCR_PI_01 != value))
				{
					this._BCR_PI_01 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BCR_PI_02", DbType="VarChar(50)")]
		public string BCR_PI_02
		{
			get
			{
				return this._BCR_PI_02;
			}
			set
			{
				if ((this._BCR_PI_02 != value))
				{
					this._BCR_PI_02 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BCR_PI_03", DbType="VarChar(50)")]
		public string BCR_PI_03
		{
			get
			{
				return this._BCR_PI_03;
			}
			set
			{
				if ((this._BCR_PI_03 != value))
				{
					this._BCR_PI_03 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BCR_PI_04", DbType="VarChar(50)")]
		public string BCR_PI_04
		{
			get
			{
				return this._BCR_PI_04;
			}
			set
			{
				if ((this._BCR_PI_04 != value))
				{
					this._BCR_PI_04 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BCR_PI_06", DbType="VarChar(50)")]
		public string BCR_PI_06
		{
			get
			{
				return this._BCR_PI_06;
			}
			set
			{
				if ((this._BCR_PI_06 != value))
				{
					this._BCR_PI_06 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BCR_PI_07", DbType="VarChar(50)")]
		public string BCR_PI_07
		{
			get
			{
				return this._BCR_PI_07;
			}
			set
			{
				if ((this._BCR_PI_07 != value))
				{
					this._BCR_PI_07 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BCR_PI_08", DbType="VarChar(50)")]
		public string BCR_PI_08
		{
			get
			{
				return this._BCR_PI_08;
			}
			set
			{
				if ((this._BCR_PI_08 != value))
				{
					this._BCR_PI_08 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BCR_PI_09", DbType="VarChar(50)")]
		public string BCR_PI_09
		{
			get
			{
				return this._BCR_PI_09;
			}
			set
			{
				if ((this._BCR_PI_09 != value))
				{
					this._BCR_PI_09 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BCR_PI_10", DbType="VarChar(50)")]
		public string BCR_PI_10
		{
			get
			{
				return this._BCR_PI_10;
			}
			set
			{
				if ((this._BCR_PI_10 != value))
				{
					this._BCR_PI_10 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BCR_PI_11", DbType="VarChar(50)")]
		public string BCR_PI_11
		{
			get
			{
				return this._BCR_PI_11;
			}
			set
			{
				if ((this._BCR_PI_11 != value))
				{
					this._BCR_PI_11 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BCR_PI_12", DbType="VarChar(50)")]
		public string BCR_PI_12
		{
			get
			{
				return this._BCR_PI_12;
			}
			set
			{
				if ((this._BCR_PI_12 != value))
				{
					this._BCR_PI_12 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BCR_PI_13", DbType="VarChar(50)")]
		public string BCR_PI_13
		{
			get
			{
				return this._BCR_PI_13;
			}
			set
			{
				if ((this._BCR_PI_13 != value))
				{
					this._BCR_PI_13 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BCR_PI_14", DbType="VarChar(50)")]
		public string BCR_PI_14
		{
			get
			{
				return this._BCR_PI_14;
			}
			set
			{
				if ((this._BCR_PI_14 != value))
				{
					this._BCR_PI_14 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BCR_PI_15", DbType="VarChar(50)")]
		public string BCR_PI_15
		{
			get
			{
				return this._BCR_PI_15;
			}
			set
			{
				if ((this._BCR_PI_15 != value))
				{
					this._BCR_PI_15 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BCR_PI_16", DbType="VarChar(50)")]
		public string BCR_PI_16
		{
			get
			{
				return this._BCR_PI_16;
			}
			set
			{
				if ((this._BCR_PI_16 != value))
				{
					this._BCR_PI_16 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BCR_PI_17", DbType="VarChar(50)")]
		public string BCR_PI_17
		{
			get
			{
				return this._BCR_PI_17;
			}
			set
			{
				if ((this._BCR_PI_17 != value))
				{
					this._BCR_PI_17 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BCR_PI_18", DbType="VarChar(50)")]
		public string BCR_PI_18
		{
			get
			{
				return this._BCR_PI_18;
			}
			set
			{
				if ((this._BCR_PI_18 != value))
				{
					this._BCR_PI_18 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BCR_PI_19", DbType="VarChar(50)")]
		public string BCR_PI_19
		{
			get
			{
				return this._BCR_PI_19;
			}
			set
			{
				if ((this._BCR_PI_19 != value))
				{
					this._BCR_PI_19 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BCR_PI_20", DbType="VarChar(50)")]
		public string BCR_PI_20
		{
			get
			{
				return this._BCR_PI_20;
			}
			set
			{
				if ((this._BCR_PI_20 != value))
				{
					this._BCR_PI_20 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BCR_PI_21", DbType="VarChar(50)")]
		public string BCR_PI_21
		{
			get
			{
				return this._BCR_PI_21;
			}
			set
			{
				if ((this._BCR_PI_21 != value))
				{
					this._BCR_PI_21 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BCR_PI_22", DbType="VarChar(50)")]
		public string BCR_PI_22
		{
			get
			{
				return this._BCR_PI_22;
			}
			set
			{
				if ((this._BCR_PI_22 != value))
				{
					this._BCR_PI_22 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BCR_PI_23", DbType="VarChar(50)")]
		public string BCR_PI_23
		{
			get
			{
				return this._BCR_PI_23;
			}
			set
			{
				if ((this._BCR_PI_23 != value))
				{
					this._BCR_PI_23 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BCR_PI_24", DbType="VarChar(50)")]
		public string BCR_PI_24
		{
			get
			{
				return this._BCR_PI_24;
			}
			set
			{
				if ((this._BCR_PI_24 != value))
				{
					this._BCR_PI_24 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BCR_PI_25", DbType="VarChar(50)")]
		public string BCR_PI_25
		{
			get
			{
				return this._BCR_PI_25;
			}
			set
			{
				if ((this._BCR_PI_25 != value))
				{
					this._BCR_PI_25 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BCR_PI_26", DbType="VarChar(50)")]
		public string BCR_PI_26
		{
			get
			{
				return this._BCR_PI_26;
			}
			set
			{
				if ((this._BCR_PI_26 != value))
				{
					this._BCR_PI_26 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BCR_PI_27", DbType="VarChar(50)")]
		public string BCR_PI_27
		{
			get
			{
				return this._BCR_PI_27;
			}
			set
			{
				if ((this._BCR_PI_27 != value))
				{
					this._BCR_PI_27 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BCR_PI_28", DbType="VarChar(50)")]
		public string BCR_PI_28
		{
			get
			{
				return this._BCR_PI_28;
			}
			set
			{
				if ((this._BCR_PI_28 != value))
				{
					this._BCR_PI_28 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BCR_PI_29", DbType="VarChar(50)")]
		public string BCR_PI_29
		{
			get
			{
				return this._BCR_PI_29;
			}
			set
			{
				if ((this._BCR_PI_29 != value))
				{
					this._BCR_PI_29 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BCR_PI_30", DbType="VarChar(50)")]
		public string BCR_PI_30
		{
			get
			{
				return this._BCR_PI_30;
			}
			set
			{
				if ((this._BCR_PI_30 != value))
				{
					this._BCR_PI_30 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BCR_PI_31", DbType="VarChar(50)")]
		public string BCR_PI_31
		{
			get
			{
				return this._BCR_PI_31;
			}
			set
			{
				if ((this._BCR_PI_31 != value))
				{
					this._BCR_PI_31 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O1_IRAT_01", DbType="VarChar(50)")]
		public string O1_IRAT_01
		{
			get
			{
				return this._O1_IRAT_01;
			}
			set
			{
				if ((this._O1_IRAT_01 != value))
				{
					this._O1_IRAT_01 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O1_IRAT_02", DbType="VarChar(50)")]
		public string O1_IRAT_02
		{
			get
			{
				return this._O1_IRAT_02;
			}
			set
			{
				if ((this._O1_IRAT_02 != value))
				{
					this._O1_IRAT_02 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O1_IRAT_03", DbType="VarChar(50)")]
		public string O1_IRAT_03
		{
			get
			{
				return this._O1_IRAT_03;
			}
			set
			{
				if ((this._O1_IRAT_03 != value))
				{
					this._O1_IRAT_03 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O1_IRAT_04", DbType="VarChar(50)")]
		public string O1_IRAT_04
		{
			get
			{
				return this._O1_IRAT_04;
			}
			set
			{
				if ((this._O1_IRAT_04 != value))
				{
					this._O1_IRAT_04 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O1_IRAT_05", DbType="VarChar(50)")]
		public string O1_IRAT_05
		{
			get
			{
				return this._O1_IRAT_05;
			}
			set
			{
				if ((this._O1_IRAT_05 != value))
				{
					this._O1_IRAT_05 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O1_IRAT_06", DbType="VarChar(50)")]
		public string O1_IRAT_06
		{
			get
			{
				return this._O1_IRAT_06;
			}
			set
			{
				if ((this._O1_IRAT_06 != value))
				{
					this._O1_IRAT_06 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O1_IRAT_07", DbType="VarChar(50)")]
		public string O1_IRAT_07
		{
			get
			{
				return this._O1_IRAT_07;
			}
			set
			{
				if ((this._O1_IRAT_07 != value))
				{
					this._O1_IRAT_07 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O1_IRAT_08", DbType="VarChar(50)")]
		public string O1_IRAT_08
		{
			get
			{
				return this._O1_IRAT_08;
			}
			set
			{
				if ((this._O1_IRAT_08 != value))
				{
					this._O1_IRAT_08 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O1_IRAT_09", DbType="VarChar(50)")]
		public string O1_IRAT_09
		{
			get
			{
				return this._O1_IRAT_09;
			}
			set
			{
				if ((this._O1_IRAT_09 != value))
				{
					this._O1_IRAT_09 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O1_IRAT_10", DbType="VarChar(50)")]
		public string O1_IRAT_10
		{
			get
			{
				return this._O1_IRAT_10;
			}
			set
			{
				if ((this._O1_IRAT_10 != value))
				{
					this._O1_IRAT_10 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O1_IRAT_11", DbType="VarChar(50)")]
		public string O1_IRAT_11
		{
			get
			{
				return this._O1_IRAT_11;
			}
			set
			{
				if ((this._O1_IRAT_11 != value))
				{
					this._O1_IRAT_11 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O1_IRAT_12", DbType="VarChar(50)")]
		public string O1_IRAT_12
		{
			get
			{
				return this._O1_IRAT_12;
			}
			set
			{
				if ((this._O1_IRAT_12 != value))
				{
					this._O1_IRAT_12 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O2_IRAT_01", DbType="VarChar(50)")]
		public string O2_IRAT_01
		{
			get
			{
				return this._O2_IRAT_01;
			}
			set
			{
				if ((this._O2_IRAT_01 != value))
				{
					this._O2_IRAT_01 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O2_IRAT_02", DbType="VarChar(50)")]
		public string O2_IRAT_02
		{
			get
			{
				return this._O2_IRAT_02;
			}
			set
			{
				if ((this._O2_IRAT_02 != value))
				{
					this._O2_IRAT_02 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HA_IRAT_01", DbType="VarChar(50)")]
		public string HA_IRAT_01
		{
			get
			{
				return this._HA_IRAT_01;
			}
			set
			{
				if ((this._HA_IRAT_01 != value))
				{
					this._HA_IRAT_01 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HA_IRAT_02", DbType="VarChar(50)")]
		public string HA_IRAT_02
		{
			get
			{
				return this._HA_IRAT_02;
			}
			set
			{
				if ((this._HA_IRAT_02 != value))
				{
					this._HA_IRAT_02 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HD_IRAT_01", DbType="VarChar(50)")]
		public string HD_IRAT_01
		{
			get
			{
				return this._HD_IRAT_01;
			}
			set
			{
				if ((this._HD_IRAT_01 != value))
				{
					this._HD_IRAT_01 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HD_IRAT_02", DbType="VarChar(50)")]
		public string HD_IRAT_02
		{
			get
			{
				return this._HD_IRAT_02;
			}
			set
			{
				if ((this._HD_IRAT_02 != value))
				{
					this._HD_IRAT_02 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SA_IRAT_01", DbType="VarChar(50)")]
		public string SA_IRAT_01
		{
			get
			{
				return this._SA_IRAT_01;
			}
			set
			{
				if ((this._SA_IRAT_01 != value))
				{
					this._SA_IRAT_01 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SA_IRAT_02", DbType="VarChar(50)")]
		public string SA_IRAT_02
		{
			get
			{
				return this._SA_IRAT_02;
			}
			set
			{
				if ((this._SA_IRAT_02 != value))
				{
					this._SA_IRAT_02 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SA_IRAT_03", DbType="VarChar(50)")]
		public string SA_IRAT_03
		{
			get
			{
				return this._SA_IRAT_03;
			}
			set
			{
				if ((this._SA_IRAT_03 != value))
				{
					this._SA_IRAT_03 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SA_IRAT_04", DbType="VarChar(50)")]
		public string SA_IRAT_04
		{
			get
			{
				return this._SA_IRAT_04;
			}
			set
			{
				if ((this._SA_IRAT_04 != value))
				{
					this._SA_IRAT_04 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SA_IRAT_05", DbType="VarChar(50)")]
		public string SA_IRAT_05
		{
			get
			{
				return this._SA_IRAT_05;
			}
			set
			{
				if ((this._SA_IRAT_05 != value))
				{
					this._SA_IRAT_05 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SA_IRAT_06", DbType="VarChar(50)")]
		public string SA_IRAT_06
		{
			get
			{
				return this._SA_IRAT_06;
			}
			set
			{
				if ((this._SA_IRAT_06 != value))
				{
					this._SA_IRAT_06 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SA_IRAT_07", DbType="VarChar(50)")]
		public string SA_IRAT_07
		{
			get
			{
				return this._SA_IRAT_07;
			}
			set
			{
				if ((this._SA_IRAT_07 != value))
				{
					this._SA_IRAT_07 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B2E_IRAT_01", DbType="VarChar(50)")]
		public string B2E_IRAT_01
		{
			get
			{
				return this._B2E_IRAT_01;
			}
			set
			{
				if ((this._B2E_IRAT_01 != value))
				{
					this._B2E_IRAT_01 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B2E_IRAT_02", DbType="VarChar(50)")]
		public string B2E_IRAT_02
		{
			get
			{
				return this._B2E_IRAT_02;
			}
			set
			{
				if ((this._B2E_IRAT_02 != value))
				{
					this._B2E_IRAT_02 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B2E_IRAT_03", DbType="VarChar(50)")]
		public string B2E_IRAT_03
		{
			get
			{
				return this._B2E_IRAT_03;
			}
			set
			{
				if ((this._B2E_IRAT_03 != value))
				{
					this._B2E_IRAT_03 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B2E_IRAT_04", DbType="VarChar(50)")]
		public string B2E_IRAT_04
		{
			get
			{
				return this._B2E_IRAT_04;
			}
			set
			{
				if ((this._B2E_IRAT_04 != value))
				{
					this._B2E_IRAT_04 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B2E_IRAT_05", DbType="VarChar(50)")]
		public string B2E_IRAT_05
		{
			get
			{
				return this._B2E_IRAT_05;
			}
			set
			{
				if ((this._B2E_IRAT_05 != value))
				{
					this._B2E_IRAT_05 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B2E_IRAT_06", DbType="VarChar(50)")]
		public string B2E_IRAT_06
		{
			get
			{
				return this._B2E_IRAT_06;
			}
			set
			{
				if ((this._B2E_IRAT_06 != value))
				{
					this._B2E_IRAT_06 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BCR_IRAT_01", DbType="VarChar(50)")]
		public string BCR_IRAT_01
		{
			get
			{
				return this._BCR_IRAT_01;
			}
			set
			{
				if ((this._BCR_IRAT_01 != value))
				{
					this._BCR_IRAT_01 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BCR_IRAT_02", DbType="VarChar(50)")]
		public string BCR_IRAT_02
		{
			get
			{
				return this._BCR_IRAT_02;
			}
			set
			{
				if ((this._BCR_IRAT_02 != value))
				{
					this._BCR_IRAT_02 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BCR_IRAT_03", DbType="VarChar(50)")]
		public string BCR_IRAT_03
		{
			get
			{
				return this._BCR_IRAT_03;
			}
			set
			{
				if ((this._BCR_IRAT_03 != value))
				{
					this._BCR_IRAT_03 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O1_MCQ1_IND", DbType="VarChar(50)")]
		public string O1_MCQ1_IND
		{
			get
			{
				return this._O1_MCQ1_IND;
			}
			set
			{
				if ((this._O1_MCQ1_IND != value))
				{
					this._O1_MCQ1_IND = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O1_MCQ1_GRP", DbType="VarChar(50)")]
		public string O1_MCQ1_GRP
		{
			get
			{
				return this._O1_MCQ1_GRP;
			}
			set
			{
				if ((this._O1_MCQ1_GRP != value))
				{
					this._O1_MCQ1_GRP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O1_MCQ1_TOT", DbType="VarChar(50)")]
		public string O1_MCQ1_TOT
		{
			get
			{
				return this._O1_MCQ1_TOT;
			}
			set
			{
				if ((this._O1_MCQ1_TOT != value))
				{
					this._O1_MCQ1_TOT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O1_MCQ2_IND", DbType="VarChar(50)")]
		public string O1_MCQ2_IND
		{
			get
			{
				return this._O1_MCQ2_IND;
			}
			set
			{
				if ((this._O1_MCQ2_IND != value))
				{
					this._O1_MCQ2_IND = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O1_MCQ2_GRP", DbType="VarChar(50)")]
		public string O1_MCQ2_GRP
		{
			get
			{
				return this._O1_MCQ2_GRP;
			}
			set
			{
				if ((this._O1_MCQ2_GRP != value))
				{
					this._O1_MCQ2_GRP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O1_MCQ2_TOT", DbType="VarChar(50)")]
		public string O1_MCQ2_TOT
		{
			get
			{
				return this._O1_MCQ2_TOT;
			}
			set
			{
				if ((this._O1_MCQ2_TOT != value))
				{
					this._O1_MCQ2_TOT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O1_MCQ3_IND", DbType="VarChar(50)")]
		public string O1_MCQ3_IND
		{
			get
			{
				return this._O1_MCQ3_IND;
			}
			set
			{
				if ((this._O1_MCQ3_IND != value))
				{
					this._O1_MCQ3_IND = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O1_MCQ3_GRP", DbType="VarChar(50)")]
		public string O1_MCQ3_GRP
		{
			get
			{
				return this._O1_MCQ3_GRP;
			}
			set
			{
				if ((this._O1_MCQ3_GRP != value))
				{
					this._O1_MCQ3_GRP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O1_MCQ3_TOT", DbType="VarChar(50)")]
		public string O1_MCQ3_TOT
		{
			get
			{
				return this._O1_MCQ3_TOT;
			}
			set
			{
				if ((this._O1_MCQ3_TOT != value))
				{
					this._O1_MCQ3_TOT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O2_MCQ1_IND", DbType="VarChar(50)")]
		public string O2_MCQ1_IND
		{
			get
			{
				return this._O2_MCQ1_IND;
			}
			set
			{
				if ((this._O2_MCQ1_IND != value))
				{
					this._O2_MCQ1_IND = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O2_MCQ1_GRP", DbType="VarChar(50)")]
		public string O2_MCQ1_GRP
		{
			get
			{
				return this._O2_MCQ1_GRP;
			}
			set
			{
				if ((this._O2_MCQ1_GRP != value))
				{
					this._O2_MCQ1_GRP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O2_MCQ1_TOT", DbType="VarChar(50)")]
		public string O2_MCQ1_TOT
		{
			get
			{
				return this._O2_MCQ1_TOT;
			}
			set
			{
				if ((this._O2_MCQ1_TOT != value))
				{
					this._O2_MCQ1_TOT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O2_MCQ2_IND", DbType="VarChar(50)")]
		public string O2_MCQ2_IND
		{
			get
			{
				return this._O2_MCQ2_IND;
			}
			set
			{
				if ((this._O2_MCQ2_IND != value))
				{
					this._O2_MCQ2_IND = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O2_MCQ2_GRP", DbType="VarChar(50)")]
		public string O2_MCQ2_GRP
		{
			get
			{
				return this._O2_MCQ2_GRP;
			}
			set
			{
				if ((this._O2_MCQ2_GRP != value))
				{
					this._O2_MCQ2_GRP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O2_MCQ2_TOT", DbType="VarChar(50)")]
		public string O2_MCQ2_TOT
		{
			get
			{
				return this._O2_MCQ2_TOT;
			}
			set
			{
				if ((this._O2_MCQ2_TOT != value))
				{
					this._O2_MCQ2_TOT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O2_MCQ3_IND", DbType="VarChar(50)")]
		public string O2_MCQ3_IND
		{
			get
			{
				return this._O2_MCQ3_IND;
			}
			set
			{
				if ((this._O2_MCQ3_IND != value))
				{
					this._O2_MCQ3_IND = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O2_MCQ3_GRP", DbType="VarChar(50)")]
		public string O2_MCQ3_GRP
		{
			get
			{
				return this._O2_MCQ3_GRP;
			}
			set
			{
				if ((this._O2_MCQ3_GRP != value))
				{
					this._O2_MCQ3_GRP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O2_MCQ3_TOT", DbType="VarChar(50)")]
		public string O2_MCQ3_TOT
		{
			get
			{
				return this._O2_MCQ3_TOT;
			}
			set
			{
				if ((this._O2_MCQ3_TOT != value))
				{
					this._O2_MCQ3_TOT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HD_MCQ1_IND", DbType="VarChar(50)")]
		public string HD_MCQ1_IND
		{
			get
			{
				return this._HD_MCQ1_IND;
			}
			set
			{
				if ((this._HD_MCQ1_IND != value))
				{
					this._HD_MCQ1_IND = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HD_MCQ1_GRP", DbType="VarChar(50)")]
		public string HD_MCQ1_GRP
		{
			get
			{
				return this._HD_MCQ1_GRP;
			}
			set
			{
				if ((this._HD_MCQ1_GRP != value))
				{
					this._HD_MCQ1_GRP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HD_MCQ1_TOT", DbType="VarChar(50)")]
		public string HD_MCQ1_TOT
		{
			get
			{
				return this._HD_MCQ1_TOT;
			}
			set
			{
				if ((this._HD_MCQ1_TOT != value))
				{
					this._HD_MCQ1_TOT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SA_MCQ1_IND", DbType="VarChar(50)")]
		public string SA_MCQ1_IND
		{
			get
			{
				return this._SA_MCQ1_IND;
			}
			set
			{
				if ((this._SA_MCQ1_IND != value))
				{
					this._SA_MCQ1_IND = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SA_MCQ1_GRP", DbType="VarChar(50)")]
		public string SA_MCQ1_GRP
		{
			get
			{
				return this._SA_MCQ1_GRP;
			}
			set
			{
				if ((this._SA_MCQ1_GRP != value))
				{
					this._SA_MCQ1_GRP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SA_MCQ1_TOT", DbType="VarChar(50)")]
		public string SA_MCQ1_TOT
		{
			get
			{
				return this._SA_MCQ1_TOT;
			}
			set
			{
				if ((this._SA_MCQ1_TOT != value))
				{
					this._SA_MCQ1_TOT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SA_MCQ2_IND", DbType="VarChar(50)")]
		public string SA_MCQ2_IND
		{
			get
			{
				return this._SA_MCQ2_IND;
			}
			set
			{
				if ((this._SA_MCQ2_IND != value))
				{
					this._SA_MCQ2_IND = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SA_MCQ2_GRP", DbType="VarChar(50)")]
		public string SA_MCQ2_GRP
		{
			get
			{
				return this._SA_MCQ2_GRP;
			}
			set
			{
				if ((this._SA_MCQ2_GRP != value))
				{
					this._SA_MCQ2_GRP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SA_MCQ2_TOT", DbType="VarChar(50)")]
		public string SA_MCQ2_TOT
		{
			get
			{
				return this._SA_MCQ2_TOT;
			}
			set
			{
				if ((this._SA_MCQ2_TOT != value))
				{
					this._SA_MCQ2_TOT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SA_MCQ3_IND", DbType="VarChar(50)")]
		public string SA_MCQ3_IND
		{
			get
			{
				return this._SA_MCQ3_IND;
			}
			set
			{
				if ((this._SA_MCQ3_IND != value))
				{
					this._SA_MCQ3_IND = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SA_MCQ3_GRP", DbType="VarChar(50)")]
		public string SA_MCQ3_GRP
		{
			get
			{
				return this._SA_MCQ3_GRP;
			}
			set
			{
				if ((this._SA_MCQ3_GRP != value))
				{
					this._SA_MCQ3_GRP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SA_MCQ3_TOT", DbType="VarChar(50)")]
		public string SA_MCQ3_TOT
		{
			get
			{
				return this._SA_MCQ3_TOT;
			}
			set
			{
				if ((this._SA_MCQ3_TOT != value))
				{
					this._SA_MCQ3_TOT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SA_MCQ4_IND", DbType="VarChar(50)")]
		public string SA_MCQ4_IND
		{
			get
			{
				return this._SA_MCQ4_IND;
			}
			set
			{
				if ((this._SA_MCQ4_IND != value))
				{
					this._SA_MCQ4_IND = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SA_MCQ4_GRP", DbType="VarChar(50)")]
		public string SA_MCQ4_GRP
		{
			get
			{
				return this._SA_MCQ4_GRP;
			}
			set
			{
				if ((this._SA_MCQ4_GRP != value))
				{
					this._SA_MCQ4_GRP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SA_MCQ4_TOT", DbType="VarChar(50)")]
		public string SA_MCQ4_TOT
		{
			get
			{
				return this._SA_MCQ4_TOT;
			}
			set
			{
				if ((this._SA_MCQ4_TOT != value))
				{
					this._SA_MCQ4_TOT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SA_MCQ5_IND", DbType="VarChar(50)")]
		public string SA_MCQ5_IND
		{
			get
			{
				return this._SA_MCQ5_IND;
			}
			set
			{
				if ((this._SA_MCQ5_IND != value))
				{
					this._SA_MCQ5_IND = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SA_MCQ5_GRP", DbType="VarChar(50)")]
		public string SA_MCQ5_GRP
		{
			get
			{
				return this._SA_MCQ5_GRP;
			}
			set
			{
				if ((this._SA_MCQ5_GRP != value))
				{
					this._SA_MCQ5_GRP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SA_MCQ5_TOT", DbType="VarChar(50)")]
		public string SA_MCQ5_TOT
		{
			get
			{
				return this._SA_MCQ5_TOT;
			}
			set
			{
				if ((this._SA_MCQ5_TOT != value))
				{
					this._SA_MCQ5_TOT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O1_PI_AVG_13", DbType="VarChar(50)")]
		public string O1_PI_AVG_13
		{
			get
			{
				return this._O1_PI_AVG_13;
			}
			set
			{
				if ((this._O1_PI_AVG_13 != value))
				{
					this._O1_PI_AVG_13 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O2_PI_AVG_13", DbType="VarChar(50)")]
		public string O2_PI_AVG_13
		{
			get
			{
				return this._O2_PI_AVG_13;
			}
			set
			{
				if ((this._O2_PI_AVG_13 != value))
				{
					this._O2_PI_AVG_13 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O1O2_PI_AVG_26", DbType="VarChar(50)")]
		public string O1O2_PI_AVG_26
		{
			get
			{
				return this._O1O2_PI_AVG_26;
			}
			set
			{
				if ((this._O1O2_PI_AVG_26 != value))
				{
					this._O1O2_PI_AVG_26 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HA_PI_AVG_04", DbType="VarChar(50)")]
		public string HA_PI_AVG_04
		{
			get
			{
				return this._HA_PI_AVG_04;
			}
			set
			{
				if ((this._HA_PI_AVG_04 != value))
				{
					this._HA_PI_AVG_04 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HD_PI_AVG_15", DbType="VarChar(50)")]
		public string HD_PI_AVG_15
		{
			get
			{
				return this._HD_PI_AVG_15;
			}
			set
			{
				if ((this._HD_PI_AVG_15 != value))
				{
					this._HD_PI_AVG_15 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SA_PI_AVG_26", DbType="VarChar(50)")]
		public string SA_PI_AVG_26
		{
			get
			{
				return this._SA_PI_AVG_26;
			}
			set
			{
				if ((this._SA_PI_AVG_26 != value))
				{
					this._SA_PI_AVG_26 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B2E_PI_AVG_30", DbType="VarChar(50)")]
		public string B2E_PI_AVG_30
		{
			get
			{
				return this._B2E_PI_AVG_30;
			}
			set
			{
				if ((this._B2E_PI_AVG_30 != value))
				{
					this._B2E_PI_AVG_30 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BCR_PI_AVG_30", DbType="VarChar(50)")]
		public string BCR_PI_AVG_30
		{
			get
			{
				return this._BCR_PI_AVG_30;
			}
			set
			{
				if ((this._BCR_PI_AVG_30 != value))
				{
					this._BCR_PI_AVG_30 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O1_IRAT_AVG_12", DbType="VarChar(50)")]
		public string O1_IRAT_AVG_12
		{
			get
			{
				return this._O1_IRAT_AVG_12;
			}
			set
			{
				if ((this._O1_IRAT_AVG_12 != value))
				{
					this._O1_IRAT_AVG_12 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O2_IRAT_AVG_02", DbType="VarChar(50)")]
		public string O2_IRAT_AVG_02
		{
			get
			{
				return this._O2_IRAT_AVG_02;
			}
			set
			{
				if ((this._O2_IRAT_AVG_02 != value))
				{
					this._O2_IRAT_AVG_02 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HA_IRAT_AVG_02", DbType="VarChar(50)")]
		public string HA_IRAT_AVG_02
		{
			get
			{
				return this._HA_IRAT_AVG_02;
			}
			set
			{
				if ((this._HA_IRAT_AVG_02 != value))
				{
					this._HA_IRAT_AVG_02 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HD_IRAT_AVG_02", DbType="VarChar(50)")]
		public string HD_IRAT_AVG_02
		{
			get
			{
				return this._HD_IRAT_AVG_02;
			}
			set
			{
				if ((this._HD_IRAT_AVG_02 != value))
				{
					this._HD_IRAT_AVG_02 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SA_IRAT_AVG_07", DbType="VarChar(50)")]
		public string SA_IRAT_AVG_07
		{
			get
			{
				return this._SA_IRAT_AVG_07;
			}
			set
			{
				if ((this._SA_IRAT_AVG_07 != value))
				{
					this._SA_IRAT_AVG_07 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B2E_IRAT_AVG_06", DbType="VarChar(50)")]
		public string B2E_IRAT_AVG_06
		{
			get
			{
				return this._B2E_IRAT_AVG_06;
			}
			set
			{
				if ((this._B2E_IRAT_AVG_06 != value))
				{
					this._B2E_IRAT_AVG_06 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BCR_IRAT_AVG_03", DbType="VarChar(50)")]
		public string BCR_IRAT_AVG_03
		{
			get
			{
				return this._BCR_IRAT_AVG_03;
			}
			set
			{
				if ((this._BCR_IRAT_AVG_03 != value))
				{
					this._BCR_IRAT_AVG_03 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O1_MCQ_AVG_03", DbType="VarChar(50)")]
		public string O1_MCQ_AVG_03
		{
			get
			{
				return this._O1_MCQ_AVG_03;
			}
			set
			{
				if ((this._O1_MCQ_AVG_03 != value))
				{
					this._O1_MCQ_AVG_03 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O2_MCQ_AVG_03", DbType="VarChar(50)")]
		public string O2_MCQ_AVG_03
		{
			get
			{
				return this._O2_MCQ_AVG_03;
			}
			set
			{
				if ((this._O2_MCQ_AVG_03 != value))
				{
					this._O2_MCQ_AVG_03 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HD_MCQ_AVG_01", DbType="VarChar(50)")]
		public string HD_MCQ_AVG_01
		{
			get
			{
				return this._HD_MCQ_AVG_01;
			}
			set
			{
				if ((this._HD_MCQ_AVG_01 != value))
				{
					this._HD_MCQ_AVG_01 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SA_MCQ_AVG_05", DbType="VarChar(50)")]
		public string SA_MCQ_AVG_05
		{
			get
			{
				return this._SA_MCQ_AVG_05;
			}
			set
			{
				if ((this._SA_MCQ_AVG_05 != value))
				{
					this._SA_MCQ_AVG_05 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B2E_MCQ_AVG_04", DbType="VarChar(50)")]
		public string B2E_MCQ_AVG_04
		{
			get
			{
				return this._B2E_MCQ_AVG_04;
			}
			set
			{
				if ((this._B2E_MCQ_AVG_04 != value))
				{
					this._B2E_MCQ_AVG_04 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BCR_MCQ_AVG_04", DbType="VarChar(50)")]
		public string BCR_MCQ_AVG_04
		{
			get
			{
				return this._BCR_MCQ_AVG_04;
			}
			set
			{
				if ((this._BCR_MCQ_AVG_04 != value))
				{
					this._BCR_MCQ_AVG_04 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BCR_ANAT_MCQ_AVG_02", DbType="VarChar(50)")]
		public string BCR_ANAT_MCQ_AVG_02
		{
			get
			{
				return this._BCR_ANAT_MCQ_AVG_02;
			}
			set
			{
				if ((this._BCR_ANAT_MCQ_AVG_02 != value))
				{
					this._BCR_ANAT_MCQ_AVG_02 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_all_NBME_avg_n4", DbType="VarChar(50)")]
		public string all_NBME_avg_n4
		{
			get
			{
				return this._all_NBME_avg_n4;
			}
			set
			{
				if ((this._all_NBME_avg_n4 != value))
				{
					this._all_NBME_avg_n4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_all_mcqs_avg_n20", DbType="VarChar(50)")]
		public string all_mcqs_avg_n20
		{
			get
			{
				return this._all_mcqs_avg_n20;
			}
			set
			{
				if ((this._all_mcqs_avg_n20 != value))
				{
					this._all_mcqs_avg_n20 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_all_irats_avg_n34", DbType="VarChar(50)")]
		public string all_irats_avg_n34
		{
			get
			{
				return this._all_irats_avg_n34;
			}
			set
			{
				if ((this._all_irats_avg_n34 != value))
				{
					this._all_irats_avg_n34 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_all_PIs_avg_n131", DbType="VarChar(50)")]
		public string all_PIs_avg_n131
		{
			get
			{
				return this._all_PIs_avg_n131;
			}
			set
			{
				if ((this._all_PIs_avg_n131 != value))
				{
					this._all_PIs_avg_n131 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BCR_NBME_final", DbType="VarChar(50)")]
		public string BCR_NBME_final
		{
			get
			{
				return this._BCR_NBME_final;
			}
			set
			{
				if ((this._BCR_NBME_final != value))
				{
					this._BCR_NBME_final = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B2E_NBME_final", DbType="VarChar(50)")]
		public string B2E_NBME_final
		{
			get
			{
				return this._B2E_NBME_final;
			}
			set
			{
				if ((this._B2E_NBME_final != value))
				{
					this._B2E_NBME_final = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O1_O2_NBME", DbType="VarChar(50)")]
		public string O1_O2_NBME
		{
			get
			{
				return this._O1_O2_NBME;
			}
			set
			{
				if ((this._O1_O2_NBME != value))
				{
					this._O1_O2_NBME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SA_NBME", DbType="VarChar(50)")]
		public string SA_NBME
		{
			get
			{
				return this._SA_NBME;
			}
			set
			{
				if ((this._SA_NBME != value))
				{
					this._SA_NBME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HA_final", DbType="VarChar(50)")]
		public string HA_final
		{
			get
			{
				return this._HA_final;
			}
			set
			{
				if ((this._HA_final != value))
				{
					this._HA_final = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HD_final", DbType="VarChar(50)")]
		public string HD_final
		{
			get
			{
				return this._HD_final;
			}
			set
			{
				if ((this._HD_final != value))
				{
					this._HD_final = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CBSE_01", DbType="VarChar(50)")]
		public string CBSE_01
		{
			get
			{
				return this._CBSE_01;
			}
			set
			{
				if ((this._CBSE_01 != value))
				{
					this._CBSE_01 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CBSE_02", DbType="VarChar(50)")]
		public string CBSE_02
		{
			get
			{
				return this._CBSE_02;
			}
			set
			{
				if ((this._CBSE_02 != value))
				{
					this._CBSE_02 = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
